// frontend/src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { authStore } from '$lib/stores/auth';
	import { goto } from '$app/navigation';
	import { Eye, EyeOff, Loader2, AlertCircle } from 'lucide-svelte';
	
	let email = '';
	let password = '';
	let showPassword = false;
	let isLoading = false;
	let errorMessage = '';
	
	// Clear any existing errors when component mounts
	onMount(() => {
		authStore.clearError();
	});
	
	// Subscribe to auth store for error handling
	$: if ($authStore.error) {
		errorMessage = $authStore.error;
		isLoading = false;
	}
	
	async function handleLogin() {
		if (!email || !password) {
			errorMessage = 'Please enter both email and password';
			return;
		}
		
		errorMessage = '';
		isLoading = true;
		
		try {
			const result = await authStore.login(email, password);
			
			if (result.success) {
				goto('/dashboard');
			} else {
				errorMessage = result.error || 'Login failed';
				isLoading = false;
			}
		} catch (error) {
			console.error('Login error:', error);
			errorMessage = 'An unexpected error occurred';
			isLoading = false;
		}
	}
	
	function handleKeyPress(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			handleLogin();
		}
	}
	
	function togglePasswordVisibility() {
		showPassword = !showPassword;
	}
</script>

<svelte:head>
	<title>Login - TenderWise AI</title>
	<meta name="description" content="Sign in to TenderWise AI - Enterprise RFP & Tendering Platform" />
</svelte:head>

<div class="animate-fadeIn">
	<!-- Header -->
	<div class="text-center mb-8">
		<h2 class="text-3xl font-bold text-white mb-2">
			Welcome back
		</h2>
		<p class="text-gray-400">
			Sign in to your TenderWise AI account
		</p>
	</div>
	
	<!-- Login Form -->
	<form on:submit|preventDefault={handleLogin} class="space-y-6">
		<!-- Email Field -->
		<div class="form-group">
			<label for="email" class="form-label">
				Email address
			</label>
			<input
				id="email"
				type="email"
				bind:value={email}
				on:keypress={handleKeyPress}
				class="input"
				placeholder="Enter your email"
				required
				disabled={isLoading}
			/>
		</div>
		
		<!-- Password Field -->
		<div class="form-group">
			<label for="password" class="form-label">
				Password
			</label>
			<div class="relative">
				<input
					id="password"
					type={showPassword ? 'text' : 'password'}
					bind:value={password}
					on:keypress={handleKeyPress}
					class="input pr-10"
					placeholder="Enter your password"
					required
					disabled={isLoading}
				/>
				<button
					type="button"
					on:click={togglePasswordVisibility}
					class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-300"
					disabled={isLoading}
				>
					{#if showPassword}
						<EyeOff size={20} />
					{:else}
						<Eye size={20} />
					{/if}
				</button>
			</div>
		</div>
		
		<!-- Error Message -->
		{#if errorMessage}
			<div class="flex items-center gap-2 p-3 bg-red-900/20 border border-red-700 rounded-md text-red-300">
				<AlertCircle size={16} />
				<span class="text-sm">{errorMessage}</span>
			</div>
		{/if}
		
		<!-- Submit Button -->
		<button
			type="submit"
			disabled={isLoading || !email || !password}
			class="w-full btn-primary flex items-center justify-center gap-2 py-3 disabled:opacity-50 disabled:cursor-not-allowed"
		>
			{#if isLoading}
				<Loader2 size={20} class="animate-spin" />
				<span>Signing in...</span>
			{:else}
				<span>Sign in</span>
			{/if}
		</button>
		
		<!-- Demo Credentials -->
		<div class="mt-6 p-4 bg-blue-900/20 border border-blue-700 rounded-md">
			<h4 class="text-sm font-medium text-blue-300 mb-2">Demo Credentials</h4>
			<div class="text-xs text-blue-200 space-y-1">
				<div>Email: <code class="bg-blue-800 px-1 rounded">rfp@kzahhar.com</code></div>
				<div>Password: <code class="bg-blue-800 px-1 rounded">password123</code></div>
			</div>
			<button
				type="button"
				on:click={() => {
					email = 'rfp@kzahhar.com';
					password = 'password123';
				}}
				class="mt-2 text-xs text-blue-300 hover:text-blue-200 underline"
				disabled={isLoading}
			>
				Fill demo credentials
			</button>
		</div>
	</form>
	
	<!-- Footer -->
	<div class="mt-8 text-center">
		<p class="text-sm text-gray-400">
			Don't have an account? 
			<a href="/contact" class="text-blue-400 hover:text-blue-300 underline">
				Contact admin
			</a>
		</p>
	</div>
</div>

<style>
	code {
		font-family: 'JetBrains Mono', monospace;
	}
</style>

// archive/old_implementation/frontend/src/app/login/page.tsx
'use client'

import React, { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/contexts/AuthContext'
import Button from '@/components/common/Button'
import Input from '@/components/common/Input'
import { EnvelopeIcon, LockClosedIcon } from '@heroicons/react/24/outline'

const LoginPage: React.FC = () => {
  const [credentials, setCredentials] = useState({
    username: '',
    password: ''
  })
  const [loading, setLoading] = useState(false)
  const { login, isAuthenticated } = useAuth()
  const router = useRouter()

  // Redirect if already authenticated
  React.useEffect(() => {
    if (isAuthenticated) {
      router.push('/dashboard')
    }
  }, [isAuthenticated, router])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!credentials.username || !credentials.password) {
      return
    }

    try {
      setLoading(true)
      await login(credentials)
    } catch (error) {
      console.error('Login failed:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setCredentials(prev => ({
      ...prev,
      [name]: value
    }))
  }

  // Demo credentials helper
  const fillDemoCredentials = () => {
    setCredentials({
      username: 'rfp@kzahhar.com',
      password: 'password123'
    })
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        {/* Header */}
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">
            TenderWise AI
          </h1>
          <h2 className="text-2xl font-semibold text-gray-700 mb-6">
            Sign in to your account
          </h2>
          <p className="text-sm text-gray-600">
            AI-powered RFP & Tendering Platform
          </p>
        </div>

        {/* Login Form */}
        <form onSubmit={handleSubmit} className="mt-8 space-y-6">
          <div className="space-y-4">
            <Input
              label="Email Address"
              type="email"
              name="username"
              value={credentials.username}
              onChange={handleChange}
              required
              autoComplete="email"
              leftIcon={<EnvelopeIcon className="h-5 w-5" />}
              placeholder="Enter your email"
            />

            <Input
              label="Password"
              type="password"
              name="password"
              value={credentials.password}
              onChange={handleChange}
              required
              autoComplete="current-password"
              leftIcon={<LockClosedIcon className="h-5 w-5" />}
              placeholder="Enter your password"
            />
          </div>

          <div className="space-y-4">
            <Button
              type="submit"
              loading={loading}
              fullWidth
              size="lg"
            >
              Sign in
            </Button>

            {/* Demo Credentials Button */}
            <Button
              type="button"
              variant="outline"
              fullWidth
              onClick={fillDemoCredentials}
              disabled={loading}
            >
              Use Demo Credentials
            </Button>
          </div>

          {/* Additional Links */}
          <div className="text-center space-y-2">
            <p className="text-sm text-gray-600">
              Demo Admin: rfp@kzahhar.com / password123
            </p>
            <div className="flex items-center justify-center space-x-4 text-sm">
              <button
                type="button"
                className="text-primary-600 hover:text-primary-500"
                onClick={() => router.push('/forgot-password')}
              >
                Forgot password?
              </button>
              <span className="text-gray-300">|</span>
              <button
                type="button"
                className="text-primary-600 hover:text-primary-500"
                onClick={() => router.push('/register')}
              >
                Create account
              </button>
            </div>
          </div>
        </form>

        {/* Features */}
        <div className="mt-8 border-t border-gray-200 pt-6">
          <div className="text-center">
            <h3 className="text-lg font-medium text-gray-900 mb-4">
              Platform Features
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm text-gray-600">
              <div className="flex items-center">
                <div className="w-2 h-2 bg-primary-500 rounded-full mr-2"></div>
                AI-Powered RFP Analysis
              </div>
              <div className="flex items-center">
                <div className="w-2 h-2 bg-primary-500 rounded-full mr-2"></div>
                Proposal Management
              </div>
              <div className="flex items-center">
                <div className="w-2 h-2 bg-primary-500 rounded-full mr-2"></div>
                Document Processing
              </div>
              <div className="flex items-center">
                <div className="w-2 h-2 bg-primary-500 rounded-full mr-2"></div>
                Risk Assessment
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default LoginPage
