// frontend/src/app/(authenticated)/users/page.tsx
"use client"

import { useState } from "react"
import { 
  Plus, 
  Search, 
  Users, 
  Settings, 
  MoreHorizontal,
  Edit,
  Trash2,
  UserCheck,
  UserX,
  Eye,
  Mail,
  Phone,
  Shield,
  Crown,
  User
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuSeparator, 
  DropdownMenuTrigger 
} from "@/components/ui/dropdown-menu"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"

// Mock data for users
const users = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@techcorp.com",
    role: "Admin",
    organization: "TechCorp Solutions",
    status: "active",
    lastLogin: "2 hours ago",
    joinDate: "2023-08-15",
    rfpsManaged: 24,
    avatar: "/api/placeholder/32/32"
  },
  {
    id: "2", 
    name: "Michael Chen",
    email: "michael.chen@globalmanuf.com",
    role: "Manager",
    organization: "Global Manufacturing Inc",
    status: "active",
    lastLogin: "1 day ago",
    joinDate: "2023-09-22",
    rfpsManaged: 18,
    avatar: "/api/placeholder/32/32"
  },
  {
    id: "3",
    name: "Emily Rodriguez", 
    email: "emily.rodriguez@hsa.org",
    role: "User",
    organization: "Healthcare Systems Alliance",
    status: "active",
    lastLogin: "3 hours ago",
    joinDate: "2023-10-05",
    rfpsManaged: 12,
    avatar: "/api/placeholder/32/32"
  },
  {
    id: "4",
    name: "David Kim",
    email: "david.kim@scg.com",
    role: "User",
    organization: "Strategic Consulting Group", 
    status: "inactive",
    lastLogin: "2 weeks ago",
    joinDate: "2023-07-18",
    rfpsManaged: 8,
    avatar: "/api/placeholder/32/32"
  },
  {
    id: "5",
    name: "Lisa Thompson",
    email: "lisa.thompson@techcorp.com",
    role: "Manager",
    organization: "TechCorp Solutions",
    status: "active",
    lastLogin: "30 minutes ago", 
    joinDate: "2023-11-12",
    rfpsManaged: 15,
    avatar: "/api/placeholder/32/32"
  }
]

export default function UsersPage() {
  const [searchTerm, setSearchTerm] = useState("")
  const [selectedRole, setSelectedRole] = useState("all")
  const [selectedStatus, setSelectedStatus] = useState("all")

  const filteredUsers = users.filter(user => {
    const matchesSearch = user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         user.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         user.organization.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesRole = selectedRole === "all" || user.role.toLowerCase() === selectedRole
    const matchesStatus = selectedStatus === "all" || user.status === selectedStatus
    return matchesSearch && matchesRole && matchesStatus
  })

  const getStatusBadge = (status: string) => {
    const variants = {
      active: { color: "bg-green-100 text-green-800", text: "Active" },
      inactive: { color: "bg-gray-100 text-gray-800", text: "Inactive" },
      pending: { color: "bg-yellow-100 text-yellow-800", text: "Pending" }
    }
    
    const config = variants[status as keyof typeof variants] || variants.active
    return <Badge className={config.color}>{config.text}</Badge>
  }

  const getRoleBadge = (role: string) => {
    const variants = {
      admin: { color: "bg-red-100 text-red-800", icon: Crown, text: "Admin" },
      manager: { color: "bg-blue-100 text-blue-800", icon: Shield, text: "Manager" },
      user: { color: "bg-purple-100 text-purple-800", icon: User, text: "User" }
    }
    
    const config = variants[role.toLowerCase() as keyof typeof variants] || variants.user
    const Icon = config.icon
    return (
      <Badge className={config.color}>
        <Icon className="w-3 h-3 mr-1" />
        {config.text}
      </Badge>
    )
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight bg-gradient-to-r from-gray-900 to-gray-600 dark:from-white dark:to-gray-300 bg-clip-text text-transparent">
            User Management
          </h1>
          <p className="text-muted-foreground text-lg">
            Manage user accounts, roles, and permissions
          </p>
        </div>
        <Button 
          size="lg"
          className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 shadow-lg hover:shadow-xl transition-all duration-200"
        >
          <Plus className="mr-2 h-4 w-4" />
          Invite User
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-6 md:grid-cols-4">
        <Card className="border-0 shadow-lg bg-gradient-to-br from-blue-50 to-blue-100 dark:from-blue-950 dark:to-blue-900">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-blue-700 dark:text-blue-300">Total Users</CardTitle>
            <div className="p-2 bg-blue-100 dark:bg-blue-800 rounded-lg">
              <Users className="h-4 w-4 text-blue-600 dark:text-blue-300" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-900 dark:text-blue-100">{users.length}</div>
            <p className="text-xs text-blue-600 dark:text-blue-400 mt-1">
              {users.filter(u => u.status === 'active').length} active users
            </p>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-green-50 to-green-100 dark:from-green-950 dark:to-green-900">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-green-700 dark:text-green-300">Active Sessions</CardTitle>
            <div className="p-2 bg-green-100 dark:bg-green-800 rounded-lg">
              <UserCheck className="h-4 w-4 text-green-600 dark:text-green-300" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-900 dark:text-green-100">
              {users.filter(u => u.status === 'active').length}
            </div>
            <p className="text-xs text-green-600 dark:text-green-400 mt-1">
              Currently online
            </p>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-purple-50 to-purple-100 dark:from-purple-950 dark:to-purple-900">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-purple-700 dark:text-purple-300">Admins</CardTitle>
            <div className="p-2 bg-purple-100 dark:bg-purple-800 rounded-lg">
              <Crown className="h-4 w-4 text-purple-600 dark:text-purple-300" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-purple-900 dark:text-purple-100">
              {users.filter(u => u.role === 'Admin').length}
            </div>
            <p className="text-xs text-purple-600 dark:text-purple-400 mt-1">
              System administrators
            </p>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-orange-50 to-orange-100 dark:from-orange-950 dark:to-orange-900">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-orange-700 dark:text-orange-300">Avg RFPs</CardTitle>
            <div className="p-2 bg-orange-100 dark:bg-orange-800 rounded-lg">
              <Settings className="h-4 w-4 text-orange-600 dark:text-orange-300" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-orange-900 dark:text-orange-100">
              {Math.round(users.reduce((sum, u) => sum + u.rfpsManaged, 0) / users.length)}
            </div>
            <p className="text-xs text-orange-600 dark:text-orange-400 mt-1">
              RFPs per user
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Search and Filters */}
      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search users..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10"
          />
        </div>
        
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline">
              <Shield className="mr-2 h-4 w-4" />
              Role: {selectedRole === 'all' ? 'All' : selectedRole}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => setSelectedRole("all")}>
              All Roles
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setSelectedRole("admin")}>
              Admin
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setSelectedRole("manager")}>
              Manager
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setSelectedRole("user")}>
              User
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline">
              <UserCheck className="mr-2 h-4 w-4" />
              Status: {selectedStatus === 'all' ? 'All' : selectedStatus}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => setSelectedStatus("all")}>
              All Status
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setSelectedStatus("active")}>
              Active
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setSelectedStatus("inactive")}>
              Inactive
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setSelectedStatus("pending")}>
              Pending
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      {/* Users Table */}
      <Card className="border-0 shadow-lg">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Users className="w-5 h-5" />
            User Directory
          </CardTitle>
          <CardDescription>
            Complete list of all platform users and their details
          </CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>User</TableHead>
                <TableHead>Organization</TableHead>
                <TableHead>Role</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>RFPs Managed</TableHead>
                <TableHead>Last Login</TableHead>
                <TableHead className="w-[100px]">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredUsers.map((user) => (
                <TableRow key={user.id} className="hover:bg-gray-50 dark:hover:bg-gray-800/50">
                  <TableCell>
                    <div className="flex items-center space-x-3">
                      <Avatar>
                        <AvatarImage src={user.avatar} alt={user.name} />
                        <AvatarFallback className="bg-gradient-to-r from-blue-600 to-purple-600 text-white text-sm">
                          {user.name.split(' ').map(n => n[0]).join('')}
                        </AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="font-medium">{user.name}</div>
                        <div className="text-sm text-muted-foreground">{user.email}</div>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-sm">{user.organization}</div>
                  </TableCell>
                  <TableCell>
                    {getRoleBadge(user.role)}
                  </TableCell>
                  <TableCell>
                    {getStatusBadge(user.status)}
                  </TableCell>
                  <TableCell>
                    <div className="font-medium">{user.rfpsManaged}</div>
                  </TableCell>
                  <TableCell>
                    <div className="text-sm">{user.lastLogin}</div>
                  </TableCell>
                  <TableCell>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon">
                          <MoreHorizontal className="h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem>
                          <Eye className="mr-2 h-4 w-4" />
                          View Profile
                        </DropdownMenuItem>
                        <DropdownMenuItem>
                          <Edit className="mr-2 h-4 w-4" />
                          Edit User
                        </DropdownMenuItem>
                        <DropdownMenuItem>
                          <Mail className="mr-2 h-4 w-4" />
                          Send Message
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        {user.status === 'active' ? (
                          <DropdownMenuItem>
                            <UserX className="mr-2 h-4 w-4" />
                            Deactivate
                          </DropdownMenuItem>
                        ) : (
                          <DropdownMenuItem>
                            <UserCheck className="mr-2 h-4 w-4" />
                            Activate
                          </DropdownMenuItem>
                        )}
                        <DropdownMenuItem className="text-destructive">
                          <Trash2 className="mr-2 h-4 w-4" />
                          Delete User
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}

// frontend/src/routes/(app)/users/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { authStore } from '$lib/stores/auth';
	import { apiClient } from '$lib/api/client';
	import { 
		Users, 
		Plus, 
		Search,
		Filter,
		MoreVertical,
		Shield,
		Mail,
		Building2
	} from 'lucide-svelte';

	let loading = true;
	let users = [];
	let searchTerm = '';
	let selectedRole = 'all';
	let error = null;

	// Check if user has access
	$: hasAccess = authStore.isAdmin();

	onMount(async () => {
		if (hasAccess) {
			await loadUsers();
		}
	});

	async function loadUsers() {
		loading = true;
		error = null;
		
		try {
			// Mock users data (in real app, would fetch from API)
			users = [
				{
					id: 1,
					email: 'rfp@kzahhar.com',
					first_name: 'Admin',
					last_name: 'User',
					role: 'super_admin',
					status: 'active',
					is_active: true,
					organization: { name: 'TenderWise' },
					last_login: '2025-01-03T10:30:00Z',
					created_at: '2024-01-01T00:00:00Z'
				},
				{
					id: 2,
					email: 'manager@company.com',
					first_name: 'John',
					last_name: 'Manager',
					role: 'manager',
					status: 'active',
					is_active: true,
					organization: { name: 'ABC Corp' },
					last_login: '2025-01-02T15:20:00Z',
					created_at: '2024-02-15T00:00:00Z'
				},
				{
					id: 3,
					email: 'user@company.com',
					first_name: 'Jane',
					last_name: 'User',
					role: 'user',
					status: 'active',
					is_active: true,
					organization: { name: 'ABC Corp' },
					last_login: '2025-01-01T09:15:00Z',
					created_at: '2024-03-10T00:00:00Z'
				}
			];
		} catch (err) {
			console.error('Failed to load users:', err);
			error = err.message || 'Failed to load users';
		} finally {
			loading = false;
		}
	}

	function getRoleBadgeClass(role) {
		const roleClasses = {
			super_admin: 'bg-red-600 text-white',
			admin: 'bg-orange-600 text-white',
			manager: 'bg-blue-600 text-white',
			user: 'bg-green-600 text-white',
			viewer: 'bg-gray-600 text-white'
		};
		return roleClasses[role] || 'bg-gray-600 text-white';
	}

	function getStatusBadgeClass(status) {
		return status === 'active' ? 'bg-green-600 text-white' : 'bg-red-600 text-white';
	}

	function formatDate(dateString) {
		return new Date(dateString).toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric',
			hour: '2-digit',
			minute: '2-digit'
		});
	}

	// Filter users based on search term and role
	$: filteredUsers = users.filter(user => {
		const matchesSearch = !searchTerm || 
			user.first_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
			user.last_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
			user.email.toLowerCase().includes(searchTerm.toLowerCase());
		
		const matchesRole = selectedRole === 'all' || user.role === selectedRole;
		
		return matchesSearch && matchesRole;
	});
</script>

<svelte:head>
	<title>Users - TenderWise AI</title>
</svelte:head>

{#if !hasAccess}
	<div class="text-center py-12">
		<Shield size={64} class="mx-auto text-gray-600 mb-4" />
		<h2 class="text-xl font-bold text-white mb-2">Access Restricted</h2>
		<p class="text-gray-400">You need administrator privileges to view users.</p>
	</div>
{:else}
	<div class="space-y-6">
		<!-- Header -->
		<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
			<div>
				<h1 class="text-3xl font-bold text-white flex items-center gap-3">
					<Users size={32} class="text-blue-400" />
					User Management
				</h1>
				<p class="text-gray-400 mt-2">Manage user accounts and permissions</p>
			</div>
			
			<div class="mt-4 sm:mt-0">
				<button class="btn-primary flex items-center gap-2">
					<Plus size={16} />
					Add User
				</button>
			</div>
		</div>

		{#if loading}
			<div class="flex items-center justify-center py-12">
				<div class="spinner w-8 h-8"></div>
				<span class="text-gray-400 ml-3">Loading users...</span>
			</div>
		{:else if error}
			<div class="card bg-red-900/20 border-red-700 text-red-300">
				<div class="flex items-center gap-3">
					<Users size={20} />
					<div>
						<h3 class="font-medium">Failed to Load Users</h3>
						<p class="text-sm text-red-200 mt-1">{error}</p>
					</div>
					<button 
						on:click={loadUsers}
						class="ml-auto btn-secondary text-sm"
					>
						Retry
					</button>
				</div>
			</div>
		{:else}
			<!-- Filters -->
			<div class="card">
				<div class="flex flex-col sm:flex-row gap-4">
					<!-- Search -->
					<div class="flex-1">
						<div class="relative">
							<Search size={20} class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
							<input
								type="text"
								placeholder="Search users..."
								bind:value={searchTerm}
								class="input pl-10"
							/>
						</div>
					</div>
					
					<!-- Role Filter -->
					<div class="sm:w-48">
						<select bind:value={selectedRole} class="input">
							<option value="all">All Roles</option>
							<option value="super_admin">Super Admin</option>
							<option value="admin">Admin</option>
							<option value="manager">Manager</option>
							<option value="user">User</option>
							<option value="viewer">Viewer</option>
						</select>
					</div>
				</div>
			</div>

			<!-- Users Table -->
			<div class="card">
				<div class="overflow-x-auto">
					<table class="w-full">
						<thead>
							<tr class="border-b border-gray-700">
								<th class="text-left py-3 px-4 text-gray-400 font-medium">User</th>
								<th class="text-left py-3 px-4 text-gray-400 font-medium">Role</th>
								<th class="text-left py-3 px-4 text-gray-400 font-medium">Organization</th>
								<th class="text-left py-3 px-4 text-gray-400 font-medium">Status</th>
								<th class="text-left py-3 px-4 text-gray-400 font-medium">Last Login</th>
								<th class="text-right py-3 px-4 text-gray-400 font-medium">Actions</th>
							</tr>
						</thead>
						<tbody class="divide-y divide-gray-700">
							{#each filteredUsers as user}
								<tr class="hover:bg-gray-800/50">
									<td class="py-4 px-4">
										<div class="flex items-center gap-3">
											<div class="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
												<span class="text-white text-sm font-medium">
													{user.first_name[0]}{user.last_name[0]}
												</span>
											</div>
											<div>
												<div class="text-white font-medium">
													{user.first_name} {user.last_name}
												</div>
												<div class="text-gray-400 text-sm flex items-center gap-1">
													<Mail size={14} />
													{user.email}
												</div>
											</div>
										</div>
									</td>
									<td class="py-4 px-4">
										<span class="badge {getRoleBadgeClass(user.role)}">
											{user.role.replace('_', ' ').toUpperCase()}
										</span>
									</td>
									<td class="py-4 px-4">
										<div class="flex items-center gap-2 text-gray-300">
											<Building2 size={16} />
											<span>{user.organization?.name || 'No Organization'}</span>
										</div>
									</td>
									<td class="py-4 px-4">
										<span class="badge {getStatusBadgeClass(user.status)}">
											{user.status.toUpperCase()}
										</span>
									</td>
									<td class="py-4 px-4 text-gray-300">
										{user.last_login ? formatDate(user.last_login) : 'Never'}
									</td>
									<td class="py-4 px-4 text-right">
										<button class="p-2 text-gray-400 hover:text-white">
											<MoreVertical size={16} />
										</button>
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
				
				{#if filteredUsers.length === 0}
					<div class="text-center py-8 text-gray-400">
						<Users size={48} class="mx-auto mb-4 opacity-50" />
						<p class="text-lg font-medium">No users found</p>
						<p class="text-sm mt-2">
							{searchTerm || selectedRole !== 'all' ? 'Try adjusting your filters' : 'No users available'}
						</p>
					</div>
				{/if}
			</div>

			<!-- User Stats -->
			<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
				<div class="card-hover">
					<div class="flex items-center justify-between">
						<div>
							<p class="text-gray-400 text-sm">Total Users</p>
							<p class="text-2xl font-bold text-white">{users.length}</p>
						</div>
						<div class="p-3 bg-blue-600 rounded-lg">
							<Users size={24} class="text-white" />
						</div>
					</div>
				</div>
				
				<div class="card-hover">
					<div class="flex items-center justify-between">
						<div>
							<p class="text-gray-400 text-sm">Active Users</p>
							<p class="text-2xl font-bold text-white">{users.filter(u => u.is_active).length}</p>
						</div>
						<div class="p-3 bg-green-600 rounded-lg">
							<Shield size={24} class="text-white" />
						</div>
					</div>
				</div>
				
				<div class="card-hover">
					<div class="flex items-center justify-between">
						<div>
							<p class="text-gray-400 text-sm">Admins</p>
							<p class="text-2xl font-bold text-white">{users.filter(u => u.role === 'admin' || u.role === 'super_admin').length}</p>
						</div>
						<div class="p-3 bg-orange-600 rounded-lg">
							<Shield size={24} class="text-white" />
						</div>
					</div>
				</div>
				
				<div class="card-hover">
					<div class="flex items-center justify-between">
						<div>
							<p class="text-gray-400 text-sm">Managers</p>
							<p class="text-2xl font-bold text-white">{users.filter(u => u.role === 'manager').length}</p>
						</div>
						<div class="p-3 bg-purple-600 rounded-lg">
							<Users size={24} class="text-white" />
						</div>
					</div>
				</div>
			</div>
		{/if}
	</div>
{/if}
